// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Coll.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Vocal;

public interface CollPrx extends com.zeroc.Ice.ObjectPrx
{
    default void add(Track t)
    {
        add(t, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void add(Track t, java.util.Map<String, String> context)
    {
        _iceI_addAsync(t, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addAsync(Track t)
    {
        return _iceI_addAsync(t, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addAsync(Track t, java.util.Map<String, String> context)
    {
        return _iceI_addAsync(t, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addAsync(Track iceP_t, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "add", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Track.ice_write(ostr, iceP_t);
                 }, null);
        return f;
    }

    default Track[] search(Track t)
    {
        return search(t, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Track[] search(Track t, java.util.Map<String, String> context)
    {
        return _iceI_searchAsync(t, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Track[]> searchAsync(Track t)
    {
        return _iceI_searchAsync(t, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Track[]> searchAsync(Track t, java.util.Map<String, String> context)
    {
        return _iceI_searchAsync(t, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Track[]> _iceI_searchAsync(Track iceP_t, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Track[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "search", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     Track.ice_write(ostr, iceP_t);
                 }, istr -> {
                     Track[] ret;
                     ret = CollectionHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void startStream(Track t)
    {
        startStream(t, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void startStream(Track t, java.util.Map<String, String> context)
    {
        _iceI_startStreamAsync(t, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> startStreamAsync(Track t)
    {
        return _iceI_startStreamAsync(t, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> startStreamAsync(Track t, java.util.Map<String, String> context)
    {
        return _iceI_startStreamAsync(t, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_startStreamAsync(Track iceP_t, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startStream", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Track.ice_write(ostr, iceP_t);
                 }, null);
        return f;
    }

    default Track[] searchTrackAndStream(Track t)
    {
        return searchTrackAndStream(t, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Track[] searchTrackAndStream(Track t, java.util.Map<String, String> context)
    {
        return _iceI_searchTrackAndStreamAsync(t, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Track[]> searchTrackAndStreamAsync(Track t)
    {
        return _iceI_searchTrackAndStreamAsync(t, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Track[]> searchTrackAndStreamAsync(Track t, java.util.Map<String, String> context)
    {
        return _iceI_searchTrackAndStreamAsync(t, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Track[]> _iceI_searchTrackAndStreamAsync(Track iceP_t, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Track[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchTrackAndStream", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     Track.ice_write(ostr, iceP_t);
                 }, istr -> {
                     Track[] ret;
                     ret = CollectionHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void pauseStream()
    {
        pauseStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void pauseStream(java.util.Map<String, String> context)
    {
        _iceI_pauseStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> pauseStreamAsync()
    {
        return _iceI_pauseStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> pauseStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_pauseStreamAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_pauseStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "pauseStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void resumeStream()
    {
        resumeStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void resumeStream(java.util.Map<String, String> context)
    {
        _iceI_resumeStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> resumeStreamAsync()
    {
        return _iceI_resumeStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> resumeStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_resumeStreamAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_resumeStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "resumeStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void stopStream()
    {
        stopStream(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void stopStream(java.util.Map<String, String> context)
    {
        _iceI_stopStreamAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> stopStreamAsync()
    {
        return _iceI_stopStreamAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> stopStreamAsync(java.util.Map<String, String> context)
    {
        return _iceI_stopStreamAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_stopStreamAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stopStream", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default Track[] getCollection()
    {
        return getCollection(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Track[] getCollection(java.util.Map<String, String> context)
    {
        return _iceI_getCollectionAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Track[]> getCollectionAsync()
    {
        return _iceI_getCollectionAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Track[]> getCollectionAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCollectionAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Track[]> _iceI_getCollectionAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Track[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCollection", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Track[] ret;
                     ret = CollectionHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CollPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), CollPrx.class, _CollPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CollPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), CollPrx.class, _CollPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CollPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), CollPrx.class, _CollPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static CollPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), CollPrx.class, _CollPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static CollPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, CollPrx.class, _CollPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static CollPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, CollPrx.class, _CollPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default CollPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (CollPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default CollPrx ice_adapterId(String newAdapterId)
    {
        return (CollPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default CollPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (CollPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default CollPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (CollPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default CollPrx ice_invocationTimeout(int newTimeout)
    {
        return (CollPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default CollPrx ice_connectionCached(boolean newCache)
    {
        return (CollPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default CollPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (CollPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CollPrx ice_secure(boolean b)
    {
        return (CollPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default CollPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (CollPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default CollPrx ice_preferSecure(boolean b)
    {
        return (CollPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default CollPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (CollPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default CollPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (CollPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default CollPrx ice_collocationOptimized(boolean b)
    {
        return (CollPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default CollPrx ice_twoway()
    {
        return (CollPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default CollPrx ice_oneway()
    {
        return (CollPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default CollPrx ice_batchOneway()
    {
        return (CollPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default CollPrx ice_datagram()
    {
        return (CollPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default CollPrx ice_batchDatagram()
    {
        return (CollPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default CollPrx ice_compress(boolean co)
    {
        return (CollPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default CollPrx ice_timeout(int t)
    {
        return (CollPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default CollPrx ice_connectionId(String connectionId)
    {
        return (CollPrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::Vocal::Coll";
    }
}
